apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Edu-BS/chainlink-node
    path: ./sealed-controller/manifests/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true