apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-database
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: chainlink-node
  source:
    repoURL: https://github.com/Edu-BS/chainlink-node
    path: ./postgresql/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true