apiVersion: apps/v1
kind: Deployment
metadata:
  name: chainlink  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chainlink
  template:
    metadata:
      labels:
        app: chainlink
    spec:
      containers:
        - name: chainlink
          image: smartcontract/chainlink:1.11.0
          args: ["local", "n", "-p", "/home/chainlink/.password", "-a", "/home/chainlink/.api"]
          ports:
            - containerPort: 6688
          envFrom:
          - configMapRef:
              name: chainlink-config
          resources: