apiVersion: v1
kind: Service
metadata:
  name: chainlink # Sets service name
  labels:
    app: chainlink # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 6688 # Sets port to run the chainlink application
  selector:
    app: chainlink