kind: ConfigMap
apiVersion: v1
metadata:
  name: poststarthook
data:
  poststart.sh: |
    #!/bin/bash
    
    psql -U postgres -c "DROP DATABASE IF EXISTS postgresdb"
    psql -U postgres -c "DROP DATABASE IF EXISTS chainlinkHardhatNetworkDB"

    psql -U postgres -c "CREATE DATABASE postgresdb"
    psql -U postgres -c "CREATE DATABASE chainlinkHardhatNetworkDB"
